### ISSUE TITLE
On what device should I install the libusb_win32 filter?

### ISSUE THREAD

**Issue by sapphicsophia** [petabyt/mlinstall#12]
I have never used libusb or anything, but I tried installing the filter on both my USB controller and my camera in the install selection box and neither made the camera detectable with mlinstall.

**Comment by petabyt** [comment]
This has been an issue for a while, I have a fix that should make it work without any libusb nonsense. Installing zadig  should work if you don't want to wait for that.

**Comment by petabyt** [comment]
Releasing native Windows version soon
