### ISSUE TITLE
drive-win errors don't get written to gui console on windows

### ISSUE THREAD

**Issue by poshul** [petabyt/mlinstall#15]
When trying to write to EOS_DIGITAL, if there is an error (in my case it was not possible to lock the drive), the specific error details are not written to the console window in the GUI. They are properly emitted to the shell if running mlinstall from a windows shell. See image for example:
![image](https://github.com/petabyt/mlinstall/assets/146827/e942db54-290d-4fba-aebb-13285c678c46)

**Comment by petabyt** [comment]
I don't see any useful information in the cmd window that could help. Overall I don't want to clutter the UI and make it too verbose (which would complicate translation, if ever needed)

The actual issue might either be some software using the drive, or possibly Explorer has copied a file to it or has done something and isn't properly ejected. I don't think I've seen this issue before.

**Comment by poshul** [comment]
Fair. If that's the intended behavior then no worries there. Perhaps add a hint to run MLInstall from the command prompt for more details? That way at least it's just one added string globally for any drive access errors that would need to be translated.

The underlying issue is almost certainly something with my weird windows setup (if I had to guess, it was WSL mounting the drive). I ended up just rebooting to linux and writing to the card there. Let me know if you'd like to me do some more testing to confirm the windows issue.

**Comment by petabyt** [comment]
> Perhaps add a hint to run MLInstall from the command prompt for more details?

That's not a bad idea, I'll go ahead and add it to the wiki page.

> it was WSL mounting the drive

I don't think WSL does this? I know all disks are usually available through /mnt, but I think it shoudl always route to the windows kernel rather than locking and mounting the filesystem.
It might just be some weird Windows bug :)
