### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by StarTakko** [petabyt/mlinstall#3]
Hi Petabyt
Is there a way to contact you directly?
I saw that in your one click install video you use a 1300D, can you help me install ML?
My problem is when inserting the SD only the red led blinks and does nothing

Thanks in advance

**Comment by petabyt** [comment]
You should know that ML isn't fully released for the 1300D. There is no guarantee that it won't break anything.
Make sure you:
- Enabled camera bootflags
- Wrote card bootflags
- Copied Magic Lantern build to card

After that it should work fine. Also see https://www.magiclantern.fm/forum/index.php?topic=17969.450

brikbusters@gmail.com
@petabyte:matrix.org
